version: '3'
networks:
  skeletonbr:
    driver: bridge

services:
  php:
    container_name: 'php-skeleton'
    networks:
      - skeletonbr
    build:
      context: ./docker/php
    volumes:
      - '.:/var/www/html'
      - './docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro'
    environment:
      COMPOSER_MEMORY_LIMIT: 2G
    working_dir: '/var/www/html'
    extra_hosts:
      # for step debugging with Xdebug
      - 'host.docker.internal:host-gateway'

  nginx:
    container_name: 'nginx-skeleton'
    image: nginx:1.23.2-alpine
    networks:
      - skeletonbr
    depends_on:
      - php
    ports:
      - 80:80
    volumes:
      - '.:/var/www/html'
      - './docker/nginx/conf.d/default.nginx:/etc/nginx/conf.d/default.conf'
